# this file is create by program.def Vgg19_0(pre_input=None):    import tvm    import numpy as np    from tvm import relay    data = pre_input if pre_input is not None else relay.var("data", shape=(15, 3, 224, 224), dtype="float32")    features_0_weight = relay.var("features.0.weight", shape=(64, 3, 3, 3), dtype="float32")    call_output0 = relay.nn.conv2d(data, features_0_weight, padding=[1, 1, 1, 1], channels=64, kernel_size=[3, 3])
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_1(pre_input=None):    import tvm    import numpy as np    from tvm import relay    features_0_bias = relay.var("features.0.bias", shape=(64, ), dtype="float32")    call_0 = pre_input if pre_input is not None else relay.var("call_0", shape=(15, 64, 224, 224), dtype="float32")    call_output0 = relay.nn.bias_add(call_0, features_0_bias)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_2(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_1 = pre_input if pre_input is not None else relay.var("call_1", shape=(15, 64, 224, 224), dtype="float32")    call_output0 = relay.nn.relu(call_1)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_3(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_2 = pre_input if pre_input is not None else relay.var("call_2", shape=(15, 64, 224, 224), dtype="float32")    features_2_weight = relay.var("features.2.weight", shape=(64, 64, 3, 3), dtype="float32")    call_output0 = relay.nn.conv2d(call_2, features_2_weight, padding=[1, 1, 1, 1], channels=64, kernel_size=[3, 3])
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_4(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_3 = pre_input if pre_input is not None else relay.var("call_3", shape=(15, 64, 224, 224), dtype="float32")    features_2_bias = relay.var("features.2.bias", shape=(64, ), dtype="float32")    call_output0 = relay.nn.bias_add(call_3, features_2_bias)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_5(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_4 = pre_input if pre_input is not None else relay.var("call_4", shape=(15, 64, 224, 224), dtype="float32")    call_output0 = relay.nn.relu(call_4)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_6(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_5 = pre_input if pre_input is not None else relay.var("call_5", shape=(15, 64, 224, 224), dtype="float32")    call_output0 = relay.nn.max_pool2d(call_5, pool_size=[2, 2], strides=[2, 2], padding=[0, 0, 0, 0])
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_7(pre_input=None):    import tvm    import numpy as np    from tvm import relay    features_5_weight = relay.var("features.5.weight", shape=(128, 64, 3, 3), dtype="float32")    call_6 = pre_input if pre_input is not None else relay.var("call_6", shape=(15, 64, 112, 112), dtype="float32")    call_output0 = relay.nn.conv2d(call_6, features_5_weight, padding=[1, 1, 1, 1], channels=128, kernel_size=[3, 3])
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_8(pre_input=None):    import tvm    import numpy as np    from tvm import relay    features_5_bias = relay.var("features.5.bias", shape=(128, ), dtype="float32")    call_7 = pre_input if pre_input is not None else relay.var("call_7", shape=(15, 128, 112, 112), dtype="float32")    call_output0 = relay.nn.bias_add(call_7, features_5_bias)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_9(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_8 = pre_input if pre_input is not None else relay.var("call_8", shape=(15, 128, 112, 112), dtype="float32")    call_output0 = relay.nn.relu(call_8)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_10(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_9 = pre_input if pre_input is not None else relay.var("call_9", shape=(15, 128, 112, 112), dtype="float32")    features_7_weight = relay.var("features.7.weight", shape=(128, 128, 3, 3), dtype="float32")    call_output0 = relay.nn.conv2d(call_9, features_7_weight, padding=[1, 1, 1, 1], channels=128, kernel_size=[3, 3])
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_11(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_10 = pre_input if pre_input is not None else relay.var("call_10", shape=(15, 128, 112, 112), dtype="float32")    features_7_bias = relay.var("features.7.bias", shape=(128, ), dtype="float32")    call_output0 = relay.nn.bias_add(call_10, features_7_bias)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_12(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_11 = pre_input if pre_input is not None else relay.var("call_11", shape=(15, 128, 112, 112), dtype="float32")    call_output0 = relay.nn.relu(call_11)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_13(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_12 = pre_input if pre_input is not None else relay.var("call_12", shape=(15, 128, 112, 112), dtype="float32")    call_output0 = relay.nn.max_pool2d(call_12, pool_size=[2, 2], strides=[2, 2], padding=[0, 0, 0, 0])
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_14(pre_input=None):    import tvm    import numpy as np    from tvm import relay    features_10_weight = relay.var("features.10.weight", shape=(256, 128, 3, 3), dtype="float32")    call_13 = pre_input if pre_input is not None else relay.var("call_13", shape=(15, 128, 56, 56), dtype="float32")    call_output0 = relay.nn.conv2d(call_13, features_10_weight, padding=[1, 1, 1, 1], channels=256, kernel_size=[3, 3])
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_15(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_14 = pre_input if pre_input is not None else relay.var("call_14", shape=(15, 256, 56, 56), dtype="float32")    features_10_bias = relay.var("features.10.bias", shape=(256, ), dtype="float32")    call_output0 = relay.nn.bias_add(call_14, features_10_bias)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_16(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_15 = pre_input if pre_input is not None else relay.var("call_15", shape=(15, 256, 56, 56), dtype="float32")    call_output0 = relay.nn.relu(call_15)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_17(pre_input=None):    import tvm    import numpy as np    from tvm import relay    features_12_weight = relay.var("features.12.weight", shape=(256, 256, 3, 3), dtype="float32")    call_16 = pre_input if pre_input is not None else relay.var("call_16", shape=(15, 256, 56, 56), dtype="float32")    call_output0 = relay.nn.conv2d(call_16, features_12_weight, padding=[1, 1, 1, 1], channels=256, kernel_size=[3, 3])
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_18(pre_input=None):    import tvm    import numpy as np    from tvm import relay    features_12_bias = relay.var("features.12.bias", shape=(256, ), dtype="float32")    call_17 = pre_input if pre_input is not None else relay.var("call_17", shape=(15, 256, 56, 56), dtype="float32")    call_output0 = relay.nn.bias_add(call_17, features_12_bias)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_19(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_18 = pre_input if pre_input is not None else relay.var("call_18", shape=(15, 256, 56, 56), dtype="float32")    call_output0 = relay.nn.relu(call_18)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_20(pre_input=None):    import tvm    import numpy as np    from tvm import relay    features_14_weight = relay.var("features.14.weight", shape=(256, 256, 3, 3), dtype="float32")    call_19 = pre_input if pre_input is not None else relay.var("call_19", shape=(15, 256, 56, 56), dtype="float32")    call_output0 = relay.nn.conv2d(call_19, features_14_weight, padding=[1, 1, 1, 1], channels=256, kernel_size=[3, 3])
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_21(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_20 = pre_input if pre_input is not None else relay.var("call_20", shape=(15, 256, 56, 56), dtype="float32")    features_14_bias = relay.var("features.14.bias", shape=(256, ), dtype="float32")    call_output0 = relay.nn.bias_add(call_20, features_14_bias)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_22(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_21 = pre_input if pre_input is not None else relay.var("call_21", shape=(15, 256, 56, 56), dtype="float32")    call_output0 = relay.nn.relu(call_21)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_23(pre_input=None):    import tvm    import numpy as np    from tvm import relay    features_16_weight = relay.var("features.16.weight", shape=(256, 256, 3, 3), dtype="float32")    call_22 = pre_input if pre_input is not None else relay.var("call_22", shape=(15, 256, 56, 56), dtype="float32")    call_output0 = relay.nn.conv2d(call_22, features_16_weight, padding=[1, 1, 1, 1], channels=256, kernel_size=[3, 3])
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_24(pre_input=None):    import tvm    import numpy as np    from tvm import relay    features_16_bias = relay.var("features.16.bias", shape=(256, ), dtype="float32")    call_23 = pre_input if pre_input is not None else relay.var("call_23", shape=(15, 256, 56, 56), dtype="float32")    call_output0 = relay.nn.bias_add(call_23, features_16_bias)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_25(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_24 = pre_input if pre_input is not None else relay.var("call_24", shape=(15, 256, 56, 56), dtype="float32")    call_output0 = relay.nn.relu(call_24)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_26(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_25 = pre_input if pre_input is not None else relay.var("call_25", shape=(15, 256, 56, 56), dtype="float32")    call_output0 = relay.nn.max_pool2d(call_25, pool_size=[2, 2], strides=[2, 2], padding=[0, 0, 0, 0])
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_27(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_26 = pre_input if pre_input is not None else relay.var("call_26", shape=(15, 256, 28, 28), dtype="float32")    features_19_weight = relay.var("features.19.weight", shape=(512, 256, 3, 3), dtype="float32")    call_output0 = relay.nn.conv2d(call_26, features_19_weight, padding=[1, 1, 1, 1], channels=512, kernel_size=[3, 3])
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_28(pre_input=None):    import tvm    import numpy as np    from tvm import relay    features_19_bias = relay.var("features.19.bias", shape=(512, ), dtype="float32")    call_27 = pre_input if pre_input is not None else relay.var("call_27", shape=(15, 512, 28, 28), dtype="float32")    call_output0 = relay.nn.bias_add(call_27, features_19_bias)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_29(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_28 = pre_input if pre_input is not None else relay.var("call_28", shape=(15, 512, 28, 28), dtype="float32")    call_output0 = relay.nn.relu(call_28)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_30(pre_input=None):    import tvm    import numpy as np    from tvm import relay    features_21_weight = relay.var("features.21.weight", shape=(512, 512, 3, 3), dtype="float32")    call_29 = pre_input if pre_input is not None else relay.var("call_29", shape=(15, 512, 28, 28), dtype="float32")    call_output0 = relay.nn.conv2d(call_29, features_21_weight, padding=[1, 1, 1, 1], channels=512, kernel_size=[3, 3])
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_31(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_30 = pre_input if pre_input is not None else relay.var("call_30", shape=(15, 512, 28, 28), dtype="float32")    features_21_bias = relay.var("features.21.bias", shape=(512, ), dtype="float32")    call_output0 = relay.nn.bias_add(call_30, features_21_bias)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_32(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_31 = pre_input if pre_input is not None else relay.var("call_31", shape=(15, 512, 28, 28), dtype="float32")    call_output0 = relay.nn.relu(call_31)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_33(pre_input=None):    import tvm    import numpy as np    from tvm import relay    features_23_weight = relay.var("features.23.weight", shape=(512, 512, 3, 3), dtype="float32")    call_32 = pre_input if pre_input is not None else relay.var("call_32", shape=(15, 512, 28, 28), dtype="float32")    call_output0 = relay.nn.conv2d(call_32, features_23_weight, padding=[1, 1, 1, 1], channels=512, kernel_size=[3, 3])
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_34(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_33 = pre_input if pre_input is not None else relay.var("call_33", shape=(15, 512, 28, 28), dtype="float32")    features_23_bias = relay.var("features.23.bias", shape=(512, ), dtype="float32")    call_output0 = relay.nn.bias_add(call_33, features_23_bias)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_35(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_34 = pre_input if pre_input is not None else relay.var("call_34", shape=(15, 512, 28, 28), dtype="float32")    call_output0 = relay.nn.relu(call_34)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_36(pre_input=None):    import tvm    import numpy as np    from tvm import relay    features_25_weight = relay.var("features.25.weight", shape=(512, 512, 3, 3), dtype="float32")    call_35 = pre_input if pre_input is not None else relay.var("call_35", shape=(15, 512, 28, 28), dtype="float32")    call_output0 = relay.nn.conv2d(call_35, features_25_weight, padding=[1, 1, 1, 1], channels=512, kernel_size=[3, 3])
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_37(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_36 = pre_input if pre_input is not None else relay.var("call_36", shape=(15, 512, 28, 28), dtype="float32")    features_25_bias = relay.var("features.25.bias", shape=(512, ), dtype="float32")    call_output0 = relay.nn.bias_add(call_36, features_25_bias)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_38(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_37 = pre_input if pre_input is not None else relay.var("call_37", shape=(15, 512, 28, 28), dtype="float32")    call_output0 = relay.nn.relu(call_37)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_39(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_38 = pre_input if pre_input is not None else relay.var("call_38", shape=(15, 512, 28, 28), dtype="float32")    call_output0 = relay.nn.max_pool2d(call_38, pool_size=[2, 2], strides=[2, 2], padding=[0, 0, 0, 0])
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_40(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_39 = pre_input if pre_input is not None else relay.var("call_39", shape=(15, 512, 14, 14), dtype="float32")    features_28_weight = relay.var("features.28.weight", shape=(512, 512, 3, 3), dtype="float32")    call_output0 = relay.nn.conv2d(call_39, features_28_weight, padding=[1, 1, 1, 1], channels=512, kernel_size=[3, 3])
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_41(pre_input=None):    import tvm    import numpy as np    from tvm import relay    features_28_bias = relay.var("features.28.bias", shape=(512, ), dtype="float32")    call_40 = pre_input if pre_input is not None else relay.var("call_40", shape=(15, 512, 14, 14), dtype="float32")    call_output0 = relay.nn.bias_add(call_40, features_28_bias)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_42(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_41 = pre_input if pre_input is not None else relay.var("call_41", shape=(15, 512, 14, 14), dtype="float32")    call_output0 = relay.nn.relu(call_41)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_43(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_42 = pre_input if pre_input is not None else relay.var("call_42", shape=(15, 512, 14, 14), dtype="float32")    features_30_weight = relay.var("features.30.weight", shape=(512, 512, 3, 3), dtype="float32")    call_output0 = relay.nn.conv2d(call_42, features_30_weight, padding=[1, 1, 1, 1], channels=512, kernel_size=[3, 3])
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_44(pre_input=None):    import tvm    import numpy as np    from tvm import relay    features_30_bias = relay.var("features.30.bias", shape=(512, ), dtype="float32")    call_43 = pre_input if pre_input is not None else relay.var("call_43", shape=(15, 512, 14, 14), dtype="float32")    call_output0 = relay.nn.bias_add(call_43, features_30_bias)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_45(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_44 = pre_input if pre_input is not None else relay.var("call_44", shape=(15, 512, 14, 14), dtype="float32")    call_output0 = relay.nn.relu(call_44)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_46(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_45 = pre_input if pre_input is not None else relay.var("call_45", shape=(15, 512, 14, 14), dtype="float32")    features_32_weight = relay.var("features.32.weight", shape=(512, 512, 3, 3), dtype="float32")    call_output0 = relay.nn.conv2d(call_45, features_32_weight, padding=[1, 1, 1, 1], channels=512, kernel_size=[3, 3])
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_47(pre_input=None):    import tvm    import numpy as np    from tvm import relay    features_32_bias = relay.var("features.32.bias", shape=(512, ), dtype="float32")    call_46 = pre_input if pre_input is not None else relay.var("call_46", shape=(15, 512, 14, 14), dtype="float32")    call_output0 = relay.nn.bias_add(call_46, features_32_bias)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_48(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_47 = pre_input if pre_input is not None else relay.var("call_47", shape=(15, 512, 14, 14), dtype="float32")    call_output0 = relay.nn.relu(call_47)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_49(pre_input=None):    import tvm    import numpy as np    from tvm import relay    features_34_weight = relay.var("features.34.weight", shape=(512, 512, 3, 3), dtype="float32")    call_48 = pre_input if pre_input is not None else relay.var("call_48", shape=(15, 512, 14, 14), dtype="float32")    call_output0 = relay.nn.conv2d(call_48, features_34_weight, padding=[1, 1, 1, 1], channels=512, kernel_size=[3, 3])
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_50(pre_input=None):    import tvm    import numpy as np    from tvm import relay    features_34_bias = relay.var("features.34.bias", shape=(512, ), dtype="float32")    call_49 = pre_input if pre_input is not None else relay.var("call_49", shape=(15, 512, 14, 14), dtype="float32")    call_output0 = relay.nn.bias_add(call_49, features_34_bias)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_51(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_50 = pre_input if pre_input is not None else relay.var("call_50", shape=(15, 512, 14, 14), dtype="float32")    call_output0 = relay.nn.relu(call_50)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_52(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_51 = pre_input if pre_input is not None else relay.var("call_51", shape=(15, 512, 14, 14), dtype="float32")    call_output0 = relay.nn.max_pool2d(call_51, pool_size=[2, 2], strides=[2, 2], padding=[0, 0, 0, 0])
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_53(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_52 = pre_input if pre_input is not None else relay.var("call_52", shape=(15, 512, 7, 7), dtype="float32")    call_output0 = relay.nn.avg_pool2d(call_52, pool_size=[1, 1], padding=[0, 0, 0, 0])
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_54(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_53 = pre_input if pre_input is not None else relay.var("call_53", shape=(15, 512, 7, 7), dtype="float32")    call_output0 = relay.nn.batch_flatten(call_53)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_55(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_54 = pre_input if pre_input is not None else relay.var("call_54", shape=(15, 25088), dtype="float32")    call_output0 = relay.nn.batch_flatten(call_54)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_56(pre_input=None):    import tvm    import numpy as np    from tvm import relay    classifier_0_bias = relay.var("classifier.0.bias", shape=(4096, ), dtype="float32")    classifier_0_weight = relay.var("classifier.0.weight", shape=(4096, 25088), dtype="float32")    call_55 = pre_input if pre_input is not None else relay.var("call_55", shape=(15, 25088), dtype="float32")    call_56 = relay.nn.dense(call_55, classifier_0_weight, units=4096)
    call_57 = relay.multiply(relay.const(1, dtype="float32"), classifier_0_bias)
    call_output0 = relay.add(call_56, call_57)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_57(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_58 = pre_input if pre_input is not None else relay.var("call_58", shape=(15, 4096), dtype="float32")    call_output0 = relay.nn.relu(call_58)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_58(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_59 = pre_input if pre_input is not None else relay.var("call_59", shape=(15, 4096), dtype="float32")    call_output0 = relay.nn.batch_flatten(call_59)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_59(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_60 = pre_input if pre_input is not None else relay.var("call_60", shape=(15, 4096), dtype="float32")    classifier_3_weight = relay.var("classifier.3.weight", shape=(4096, 4096), dtype="float32")    classifier_3_bias = relay.var("classifier.3.bias", shape=(4096, ), dtype="float32")    call_61 = relay.nn.dense(call_60, classifier_3_weight, units=4096)
    call_62 = relay.multiply(relay.const(1, dtype="float32"), classifier_3_bias)
    call_output0 = relay.add(call_61, call_62)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_60(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_63 = pre_input if pre_input is not None else relay.var("call_63", shape=(15, 4096), dtype="float32")    call_output0 = relay.nn.relu(call_63)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_61(pre_input=None):    import tvm    import numpy as np    from tvm import relay    call_64 = pre_input if pre_input is not None else relay.var("call_64", shape=(15, 4096), dtype="float32")    call_output0 = relay.nn.batch_flatten(call_64)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]def Vgg19_62(pre_input=None):    import tvm    import numpy as np    from tvm import relay    classifier_6_bias = relay.var("classifier.6.bias", shape=(1000, ), dtype="float32")    call_66 = relay.nn.dense(call_classifier_6_weight, call_65, units=1000)
    call_67 = relay.multiply(relay.const(1, dtype="float32"), classifier_6_bias)
    call_output0 = relay.add(call_66, call_67)
    return call_output0 if not isinstance(call_output0,tvm.relay.expr.TupleWrapper) else call_output0[0]